[workspace]
members = [
	"bee-api",
	"bee-common-ext",
	"bee-crypto",
	"bee-ledger",
	"bee-network",
	"bee-node",
	"bee-peering",
	"bee-pow",
	"bee-protocol",
	"bee-signing/bee-signing",
	"bee-snapshot",
	# "bee-storage",
	"bee-tangle",
	"bee-ternary-ext",
	"bee-test",
	"bee-transaction",
]
