[workspace]
members = [
	"bee-bundle",
	"bee-common",
	"bee-crypto",
	"bee-main",
	"bee-network",
	"bee-pow",
	"bee-signing",
	"bee-storage",
	"bee-tangle",
	"bee-ternary",
	"bee-storage",
	"bee-storage-backends",

	# ONLY TEMPORARY
	"iota-conversion",
	"iota-constants",
	"iota-crypto",
]
