[package]
name = "bee-transaction"
version = "0.1.0-alpha"
authors = ["IOTA Stiftung"]
edition = "2018"
description = ""
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "transaction"]
homepage = "https://www.iota.org"

[dependencies]
bee-crypto = { path = "../bee-crypto" }
bee-signing = { path = "../bee-signing" }
bee-ternary = { git = "https://github.com/iotaledger/bee.git", features = ["serde1"] }
bee-ternary-ext = { path = "../bee-ternary-ext" }
serde = { version = "1.0", optional = true }

[dev-dependencies]
serde_json = "1.0"

[features]
serde1 = ["serde"]
