# Duplicate this file to config.toml to use it

[logger]
color_enabled = true
[[logger.outputs]]
name  = "stdout"
level = "info"

[network]
binding_addr        = "0.0.0.0"
binding_port        = 15600
reconnect_interval  = 60

[peering.manual]
limit     = 5
peers     = [ ]

[protocol]
mwm = 14
[protocol.coordinator]
public_key_count  = 2
[[protocol.coordinator.public_key_ranges]]
public_key  = "ed3c3f1a319ff4e909cf2771d79fece0ac9bd9fd2ee49ea6c0885c9cb3b1248c"
start       = 0
end         = 0
[[protocol.coordinator.public_key_ranges]]
public_key  = "f6752f5f46a53364e2ee9c4d662d762a81efd51010282a75cd6bd03f28ef349c"
start       = 0
end         = 0
[protocol.workers]
status_interval = 10

[snapshot]
path              = "./snapshots/alphanet/export.bin"
download_urls     = [
  "https://x-vps.com/export.bin",
  "https://dbfiles.iota.org/mainnet/hornet/latest-export.bin"
]
depth             = 50
interval_synced   = 50
interval_unsynced = 1000
[snapshot.pruning]
enabled = true
delay   = 60480

[database]
path = "./database/alphanet"
