# Duplicate this file to config.toml to use it

[logger]
color_enabled = true
[[logger.outputs]]
name  = "stdout"
level = "info"

[network]
binding_addr        = "0.0.0.0"
binding_port        = 15600
reconnect_interval  = 60

[peering]
[peering.manual]
limit     = 5
peers     = [ ]

[protocol]
mwm = 14
[protocol.coordinator]
depth           = 24
public_key      = "UDYXTZBE9GZGPM9SSQV9LTZNDLJIZMPUVVXYXFYVBLIEUHLSEWFTKZZLXYRHHWVQV9MNNX9KZC9D9UZWZ"
security_level  = 2
sponge_type     = "kerl"
[protocol.workers]
status_interval = 10

[snapshot.local]
file_path     = "./snapshots/mainnet/export.bin"
download_urls = [
  "https://ls.manapotion.io/export.bin",
  "https://x-vps.com/export.bin",
  "https://dbfiles.iota.org/mainnet/hornet/latest-export.bin"
]
[snapshot.pruning]
enabled = true
delay   = 60480
